/** Contract synthesis for `momus contract` (mirrors server-side logic). */
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import * as ts from 'typescript';

export function synthesizeForCli(
  root: string,
  targetPath: string,
  symbolName: string | undefined,
  framework: string,
): { template: string } | { error: string } {
  const abs = resolve(root, targetPath);
  if (!existsSync(abs)) return { error: `NOT_FOUND: ${targetPath} does not exist under ${root}` };
  const source = readFileSync(abs, 'utf8');
  const sf = ts.createSourceFile(abs, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const classes = sf.statements.filter((s): s is ts.ClassDeclaration => ts.isClassDeclaration(s) && !!s.name);
  const cls = symbolName ? classes.find((s) => s.name?.text === symbolName) : classes[0];
  if (!cls?.name) return { error: `no class found in ${targetPath}` };
  const className = cls.name.text;
  const lines: string[] = [];
  for (const m of cls.members) {
    if (ts.isMethodDeclaration(m)) {
      const flags = ts.getCombinedModifierFlags(m);
      const isPublicInstance = !(
        flags &
        (ts.ModifierFlags.Private | ts.ModifierFlags.Protected | ts.ModifierFlags.Static)
      );
      if (!isPublicInstance) continue;
      const name = m.name.getText(sf);
      const params = m.parameters
        .map((p) => `${p.name.getText(sf)}${p.questionToken ? '?' : ''}${p.type ? ': ' + p.type.getText(sf) : ''}`)
        .join(', ');
      const ret = m.type ? m.type.getText(sf) : 'unknown';
      lines.push(`  // ${name}(${params}): ${ret}`);
      if (framework === 'vitest' || framework === 'jest') {
        lines.push(`  ${name}: ${framework === 'vitest' ? 'vi' : 'jest'}.fn().mockReturnValue(undefined),`);
      } else {
        lines.push(`  ${name}: (${params}) => undefined,`);
      }
    } else if (ts.isGetAccessorDeclaration(m)) {
      const name = m.name.getText(sf);
      lines.push(`  // get ${name}(): ${m.type?.getText(sf) ?? 'unknown'}`);
      lines.push(`  get ${name}() { return undefined; },`);
    }
  }
  const template = [
    `// Generated by momus contract — ${className} (${framework})`,
    `// Contract verified against ${targetPath}`,
    `const ${className[0]!.toLowerCase() + className.slice(1)}Mock = {`,
    ...lines,
    `} satisfies Partial<${className}>;`,
  ].join('\n');
  return { template };
}
